sudo: true
language: python
python: 3.6
install:
  - pip install tox-travis codacy-coverage
script:
  - bash bin/versionCheck.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
  - tox
  - bin/create_parser
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master
before_deploy:
  - sed --expression "s|GIT_HASH|$TRAVIS_COMMIT|g" --in-place **/version.py
after_success:
  - python-codacy-coverage -r reports/coverage.xml
